name: Go CI

on:
  push:
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod tidy

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test ./... -v
